# Use Node.js v16 as the base image
FROM node:20.5.0

# Set the working directory
WORKDIR /app/frontend

# Copy package.json and package-lock.json before other files
# COPY package*.json ./

# Install dependencies
# RUN npm install -g npm@10.2.5


# Copy all files
# COPY . .

# Expose the port the app will run on
EXPOSE 8080

# Command to run the application
# CMD ["npm", "run", "serve"]