@Host=http://localhost:3000
@myToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9hYnVzaGFyIiwiaWF0IjoxNjk3ODgzOTUwfQ.wrhXtS0BIUXGqkHK-GqIS-O9mal_hbvvJq_ZWH-qE5A
@akeryanToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrZXJ5YW4iLCJpYXQiOjE2OTc4ODM2MDR9.UJuF_fTDSeieZJFadUzR7RbkdCbjWryqg2RNq8UCU4E
###Get my user
GET http://localhost:3000/auth/me
Authorization: Bearer {{myToken}}

### Get akeryan user
GET http://localhost:3000/auth/me
Authorization: Bearer {{akeryanToken}}


### sign up
POST http://localhost:3000/users/signup
Content-Type: application/json

{
	"email": "abcd@abcd.com",
	"password": "lol",
	"username": "aalhamel"
}

### authentication
GET http://localhost:3000/auth/42

### find user by id
GET http://localhost:3000/users/

###find all users

GET http://localhost:3000/users?userName=oabushar

### print goodbye
GET http://localhost:3000/hi

### remove user
DELETE http://localhost:3000/users/3

### generate qr code
GET  http://localhost:3000/auth/2fa/generate

### authenticate 2fa
GET  http://localhost:3000/auth/2fa/authenticate

### send friend request to user with id: 
POST http://localhost:3000/friend-requests/4
Authorization: Bearer {{myToken}}

### check friend requests
GET http://localhost:3000/friend-requests/my-friend-requests
Authorization: Bearer {{akeryanToken}}

### accept friend request
PATCH http://localhost:3000/friend-requests/10/accept

### reject friend request
PATCH http://localhost:3000/friend-requests/8/reject

### Delete friend
DELETE http://localhost:3000/users/2/friends/1

### Get oabushar achievements
GET http://localhost:3000/users/1/achievements
Authorization: Bearer {{myToken}}

### Give oabushar achievement
PATCH http://localhost:3000/users/3/giveAchievement/First%20Win
Authorization: Bearer {{myToken}}
