###Get my user
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9hYnVzaGFyIiwiaWF0IjoxNjk3MTE1Mzg5fQ.HLbMYfXoSsuV6LasSMZnX9l9g4aSj9WxDt3o7turDdo

### Get  user
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYWwtenViIiwiaWF0IjoxNjk2ODM5NjY2fQ.JD1thTJPoImNvB0kWDNOjo1qRZg7KdpWrhob6lD2K90


### sign up
POST http://localhost:3000/users/signup
Content-Type: application/json

{
	"email": "abcd@abcd.com",
	"password": "lol",
	"username": "aalhamel"
}

### authentication
GET http://localhost:3000/auth/42

### find user by id
GET http://localhost:3000/users/

###find all users

GET http://localhost:3000/users?userName=mawad

### print goodbye
GET http://localhost:3000/hi

### remove user
DELETE http://localhost:3000/users/9

### generate qr code
GET  http://localhost:3000/auth/2fa/generate

### authenticate 2fa
GET  http://localhost:3000/auth/2fa/authenticate

### send friend request to user with id: 
POST http://localhost:3000/friend-requests/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9hYnVzaGFyIiwiaWF0IjoxNjk2ODM5NTYxfQ.0KE5GjriSoWDstut-A3zH7X9aLRxks9hipa4rzfSLyE

### check friend requests
GET http://localhost:3000/friend-requests/2

### accept friend request
PATCH http://localhost:3000/friend-requests/9/accept

### reject friend request
PATCH http://localhost:3000/friend-requests/8/reject

### Delete friend
DELETE http://localhost:3000/users/2/friends/1

### Get oabushar achievements
GET http://localhost:3000/users/1/achievements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9hYnVzaGFyIiwiaWF0IjoxNjk3MTE1Mzg5fQ.HLbMYfXoSsuV6LasSMZnX9l9g4aSj9WxDt3o7turDdo

### Give oabushar achievement
PATCH http://localhost:3000/users/1/giveAchievement/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9hYnVzaGFyIiwiaWF0IjoxNjk3MTE1Mzg5fQ.HLbMYfXoSsuV6LasSMZnX9l9g4aSj9WxDt3o7turDdo
